build: false

image:
  - Ubuntu
  - Visual Studio 2015


for:
-
  matrix:
    only:
        - image: Visual Studio 2015
        
  install:
     - set PATH=C:\Miniconda;C:\Miniconda\\Scripts;%PATH%
     - conda config --set always_yes yes --set changeps1 no
     - conda update -q conda
     - conda info -a
     - sudo apt install libglib2.0-dev
     - conda create -q -n test-environment python=2.7 numpy scipy nose 
     - activate test-environment
     - pip install coverage
     - python setup.py install
     - cd tests
     - python setup.py install
-
  matrix:
    only:
        - image: Ubuntu
        
  install:
     - wget http://repo.continuum.io/miniconda/Miniconda-3.9.1-Linux-x86_64.sh -O miniconda.sh
     - chmod +x miniconda.sh && ./miniconda.sh -b
     - export PATH=/home/appveyor/miniconda/bin:$PATH
     - conda update --yes conda
     - deps="nomkl pip numpy scipy"
     - conda create -p $HOME/py --yes $deps python=2.7
     - export PATH=$HOME/py/bin:$PATH
     - sudo apt-get install -qq libatlas-base-dev gfortran
     - export ATLAS="/usr/lib/atlas-base/libatlas.so"
     - python setup.py install
     - cd tests
     - python setup.py install
     - pip install nose


test_script:
  - nosetests
